version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    ports:
      - "3001:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://localhost:8000
    networks:
      - switch-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  switch-network:
    driver: bridge

volumes:
  frontend-build: 