# IMPORTANT: This is a template configuration file.
# Copy this to docker-compose.yml and adjust settings as needed.
# Common Issues:
# 1. Port Mapping: Do not expose frontend port as it's accessed through the main Nginx reverse proxy
# 2. Network Configuration: Must be on the same network as the main Nginx reverse proxy
# 3. Environment Variables: Ensure proper API URLs and environment settings

version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    # NOTE: Do not expose ports - the service is accessed through the main Nginx reverse proxy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      # Update API URL to match your domain and path
      - VITE_API_URL=https://your-domain.com/app/switch/api
    networks:
      # Must be on the same network as the main Nginx reverse proxy
      - app-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-build:/usr/share/nginx/html
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
    # This network must match the main docker-compose network
    external: true
    name: docker-apps_app-network

volumes:
  frontend-build: 